### ISSUE TITLE
What if I want to eat squares?

### ISSUE THREAD

**Issue by lazerjay7** [oh-facts/eat-my-balls#1]

**Comment by oh-facts** [comment]
At first I thought you were naive for suggesting wanting squares, when balls are superior, but then after giving it more thought, I realized I only felt this way because of my insecurities. I have lots of balls, hundreds maybe, but zero squares. I should quit being silly and add some squares. Squares might still be inferior, but at least they have a purpose - a point. Four points to be exact. 

Eat my balls 1.0.1 will be truly amazing.

**Comment by oh-facts** [comment]
Squares have been added. Also, eating a square resets score to zero since the name of the game is eat my balls, bot eat my squares. PS: I love templates and thats the only reason I will never switch to rust even though superior build system.
